"""
Tutorial Generation Master Script
===================================

Generates all tutorial videos (MP4) and screenshot guides (HTML).

Usage:
    python scripts/tutorials/generate_all.py                          # All tutorials
    python scripts/tutorials/generate_all.py --category admin         # Admin only
    python scripts/tutorials/generate_all.py --category investor      # Investor portal only
    python scripts/tutorials/generate_all.py --category launching     # Launch tutorials only
    python scripts/tutorials/generate_all.py --tutorial admin_fund_flow  # Single tutorial
    python scripts/tutorials/generate_all.py --skip-video             # Guides only (no ffmpeg needed)
    python scripts/tutorials/generate_all.py --dry-run                # Show what would be generated
    python scripts/tutorials/generate_all.py --deploy                 # Copy to frontend public/
"""

import argparse
import importlib
import shutil
import subprocess
import sys
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scripts.tutorials.config import (
    TUTORIAL_REGISTRY, CATEGORY_LABELS,
    OUTPUT_DIR, VIDEO_DIR, GUIDE_DIR, SCREENSHOT_DIR,
    FRONTEND_PUBLIC_DIR, DEV_DB_PATH,
    get_tutorials_by_category, ensure_output_dirs, check_ffmpeg,
)


def verify_dependencies(skip_video=False):
    """Check that all required dependencies are installed."""
    issues = []

    # Python packages
    for pkg in ['PIL', 'jinja2']:
        try:
            importlib.import_module(pkg)
        except ImportError:
            issues.append(f"Missing Python package: {pkg}")

    if not skip_video and not check_ffmpeg():
        issues.append("ffmpeg not found on PATH (needed for video generation)")

    return issues


def refresh_dev_database():
    """Recreate the dev database with fresh synthetic data."""
    setup_script = PROJECT_ROOT / 'scripts' / 'setup' / 'setup_test_database.py'
    if not setup_script.exists():
        print("  WARNING: setup_test_database.py not found, skipping DB refresh")
        return False

    print("  Refreshing dev database...")
    result = subprocess.run(
        [sys.executable, str(setup_script), '--env', 'dev'],
        cwd=str(PROJECT_ROOT),
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode == 0:
        print(f"  Dev database ready: {DEV_DB_PATH}")
        return True
    else:
        print(f"  WARNING: DB refresh failed: {result.stderr[:200]}")
        return False


def get_recorder_class(tutorial_id):
    """Dynamically import and return the recorder class for a tutorial."""
    meta = TUTORIAL_REGISTRY[tutorial_id]
    module_path = meta['module']

    module = importlib.import_module(module_path)

    # Find the recorder class (subclass of BaseRecorder)
    from scripts.tutorials.base_recorder import BaseRecorder
    for attr_name in dir(module):
        attr = getattr(module, attr_name)
        if (isinstance(attr, type)
                and issubclass(attr, BaseRecorder)
                and attr is not BaseRecorder):
            return attr

    raise RuntimeError(f"No BaseRecorder subclass found in {module_path}")


def generate_metadata_js():
    """Generate the tutorialData.js file for the React frontend."""
    lines = ['// Auto-generated by scripts/tutorials/generate_all.py',
             '// Do not edit manually.',
             '',
             'export const TUTORIALS = [']

    for tid, meta in TUTORIAL_REGISTRY.items():
        video_exists = (VIDEO_DIR / f'{tid}.mp4').exists()
        guide_exists = (GUIDE_DIR / f'{tid}.html').exists()

        lines.append('  {')
        lines.append(f"    id: '{tid}',")
        lines.append(f"    title: '{meta['title']}',")
        lines.append(f"    description: '{meta['description']}',")
        lines.append(f"    category: '{meta['category']}',")
        lines.append(f"    duration: '{meta['duration']}',")
        if video_exists:
            lines.append(f"    videoUrl: '/tutorials/videos/{tid}.mp4',")
        else:
            lines.append(f"    videoUrl: null,")
        if guide_exists:
            lines.append(f"    guideUrl: '/tutorials/guides/{tid}.html',")
        else:
            lines.append(f"    guideUrl: null,")
        lines.append('  },')

    lines.append('];')
    lines.append('')

    output_path = (
        PROJECT_ROOT / 'apps' / 'investor_portal' / 'frontend'
        / 'investor_portal' / 'src' / 'tutorialData.js'
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines), encoding='utf-8')
    print(f"  Metadata: {output_path}")
    return output_path


def deploy_to_frontend():
    """Copy generated tutorials to the frontend public directory."""
    print("\nDeploying to frontend...")

    # Create target dirs
    videos_target = FRONTEND_PUBLIC_DIR / 'videos'
    guides_target = FRONTEND_PUBLIC_DIR / 'guides'
    videos_target.mkdir(parents=True, exist_ok=True)
    guides_target.mkdir(parents=True, exist_ok=True)

    # Copy videos
    video_count = 0
    for mp4 in VIDEO_DIR.glob('*.mp4'):
        shutil.copy2(mp4, videos_target / mp4.name)
        video_count += 1

    # Copy guides
    guide_count = 0
    for html in GUIDE_DIR.glob('*.html'):
        shutil.copy2(html, guides_target / html.name)
        guide_count += 1

    print(f"  Copied {video_count} videos + {guide_count} guides to {FRONTEND_PUBLIC_DIR}")


def print_summary():
    """Print a summary of generated files."""
    print("\n" + "=" * 60)
    print("Generation Summary")
    print("=" * 60)

    total_video_size = 0
    total_guide_size = 0

    for tid in TUTORIAL_REGISTRY:
        video = VIDEO_DIR / f'{tid}.mp4'
        guide = GUIDE_DIR / f'{tid}.html'

        v_status = ''
        g_status = ''

        if video.exists():
            size = video.stat().st_size
            total_video_size += size
            v_status = f'MP4 ({size / 1024:.0f} KB)'
        else:
            v_status = '(no video)'

        if guide.exists():
            size = guide.stat().st_size
            total_guide_size += size
            g_status = f'HTML ({size / 1024:.0f} KB)'
        else:
            g_status = '(no guide)'

        print(f"  {tid:35s} {v_status:20s} {g_status}")

    print()
    print(f"  Total video: {total_video_size / (1024*1024):.1f} MB")
    print(f"  Total guides: {total_guide_size / (1024*1024):.1f} MB")
    print(f"  Output: {OUTPUT_DIR}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate tutorial videos and screenshot guides.'
    )
    parser.add_argument(
        '--category',
        choices=list(CATEGORY_LABELS.keys()) + ['getting-started'],
        help='Generate only tutorials in this category',
    )
    parser.add_argument(
        '--tutorial',
        help='Generate a single tutorial by ID',
    )
    parser.add_argument(
        '--skip-video', action='store_true',
        help='Skip video generation (produce HTML guides only)',
    )
    parser.add_argument(
        '--dry-run', action='store_true',
        help='Show what would be generated without actually doing it',
    )
    parser.add_argument(
        '--deploy', action='store_true',
        help='Copy generated files to frontend public/ directory',
    )
    parser.add_argument(
        '--no-db-refresh', action='store_true',
        help='Skip dev database refresh',
    )

    args = parser.parse_args()

    print("=" * 60)
    print("Tovito Trader Tutorial Generator")
    print("=" * 60)

    # Determine which tutorials to generate
    if args.tutorial:
        if args.tutorial not in TUTORIAL_REGISTRY:
            print(f"ERROR: Unknown tutorial '{args.tutorial}'")
            print(f"Available: {', '.join(TUTORIAL_REGISTRY.keys())}")
            sys.exit(1)
        tutorial_ids = [args.tutorial]
    elif args.category:
        tutorial_ids = get_tutorials_by_category(args.category)
        if not tutorial_ids:
            print(f"ERROR: No tutorials in category '{args.category}'")
            sys.exit(1)
    else:
        tutorial_ids = list(TUTORIAL_REGISTRY.keys())

    print(f"\nTutorials to generate ({len(tutorial_ids)}):")
    for tid in tutorial_ids:
        meta = TUTORIAL_REGISTRY[tid]
        print(f"  [{meta['category']:15s}] {tid}: {meta['title']}")

    if args.dry_run:
        print("\n(Dry run — no files generated)")
        return

    # Verify dependencies
    print("\nChecking dependencies...")
    issues = verify_dependencies(skip_video=args.skip_video)
    if issues:
        for issue in issues:
            print(f"  ERROR: {issue}")
        sys.exit(1)
    print("  All dependencies OK")

    # Ensure output directories
    ensure_output_dirs()

    # Refresh dev database
    if not args.no_db_refresh:
        refresh_dev_database()

    # Generate tutorials
    start_time = time.time()
    success_count = 0
    fail_count = 0

    for tid in tutorial_ids:
        try:
            recorder_class = get_recorder_class(tid)
            recorder = recorder_class(tid)
            recorder.run(skip_video=args.skip_video)
            success_count += 1
        except Exception as e:
            print(f"\n  FAILED: {tid}: {e}")
            fail_count += 1

    elapsed = time.time() - start_time

    # Generate frontend metadata
    print("\nGenerating frontend metadata...")
    generate_metadata_js()

    # Deploy if requested
    if args.deploy:
        deploy_to_frontend()

    # Summary
    print_summary()
    print(f"\n  Generated: {success_count} OK, {fail_count} failed")
    print(f"  Time: {elapsed:.1f} seconds")

    if fail_count > 0:
        sys.exit(1)


if __name__ == '__main__':
    main()
